### ISSUE TITLE
`nlmixr2lib` `addDepot` always adds bioavailibility (may not wish to have)

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2lib#74]
Also has initial values that cannot be customized.

**Comment by billdenney** [comment]
@mattfidler and @john-harrold, What would you think about separating these into several different functions:

* `addDepot()` / `removeDepot()`
* `addBioavailability()` / `removeBioavailability()`
* `addLagTime()` / `removeLagTime()`

That seems like it would give users the maximum control.  Perhaps `addDepot()` also optionally calls `addBioavailability()` and `addLagTime()` based on user inputs.

And, what would you think about having the initial value set to `NA` instead of the boolean control of adding or not (that would remove a few arguments)?

**Comment by mattfidler** [comment]
I must say I am a bit stuck on reworking `rxode2` now (merging `rxode2parse`, `rxode2random`, `rxode2et` and `rxode2`).

If you want to take this on then I 100% agree (I will even review the code).  I have added these to help the shiny model library.  If you change these then I will adapt the shiny input with Emmanuel.

**Comment by mattfidler** [comment]
> And, what would you think about having the initial value set to NA instead of the boolean control of adding or not (that would remove a few arguments)?

This is fine with me too.

**Comment by mattfidler** [comment]
> Perhaps addDepot() also optionally calls addBioavailability() and addLagTime() based on user inputs.

To me this is not needed; I think that I think that adding these would be easy enough.
